apiVersion: v1
kind: Service
metadata:
  name: doc-2-storage-service
  namespace: d2p
spec:
  type: NodePort
  selector:
    app: doc-2-pdf-storage
  ports:
    - protocol: TCP
      port: 80
      targetPort: storage-api-port
