apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-2-pdf
  labels:
    app: doc-2-pdf
  namespace: d2p
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doc-2-pdf
  template:
    metadata:
      labels:
        app: doc-2-pdf
    spec:
      containers:
        - name: doc-2-pdf
          image: utkarsh1905/doc2pdf:latest
          resources:
            requests:
              memory: "1Gi"
              cpu: 2
            limits:
              memory: "1Gi"
              cpu: 3
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: api-port
          envFrom:
            - secretRef:
                name: doc-2-pdf-secrets
