apiVersion: v1
kind: Service
metadata:
  name: doc-2-pdf-service
  namespace: d2p
spec:
  type: NodePort
  selector:
    app: doc-2-pdf
  ports:
    - protocol: TCP
      port: 80
      targetPort: api-port
